import type { DetectionResult } from "./types";

export const MOCK_INVENTORIES: DetectionResult[] = [
  {
    items: [
      {
        name: "roma tomato",
        quantity: 4,
        unit: "count",
        quantityKind: "exact",
        category: "produce",
        confidence: 0.94,
      },
      {
        name: "yellow onion",
        quantity: 2,
        unit: "count",
        quantityKind: "exact",
        category: "produce",
        confidence: 0.9,
      },
      {
        name: "garlic",
        quantity: 1,
        unit: "head",
        quantityKind: "estimate",
        category: "produce",
        confidence: 0.82,
      },
      {
        name: "spaghetti",
        quantity: 500,
        unit: "g",
        quantityKind: "estimate",
        category: "grain",
        confidence: 0.88,
      },
      {
        name: "olive oil",
        quantity: 750,
        unit: "ml",
        quantityKind: "estimate",
        category: "condiment",
        confidence: 0.8,
      },
      {
        name: "parmesan",
        quantity: 200,
        unit: "g",
        quantityKind: "estimate",
        category: "dairy",
        confidence: 0.71,
      },
      {
        name: "basil",
        quantity: 1,
        unit: "bunch",
        quantityKind: "estimate",
        category: "produce",
        confidence: 0.66,
      },
    ],
    notes: "Mock inventory: pasta-friendly pantry photo.",
  },
  {
    items: [
      {
        name: "eggs",
        quantity: 6,
        unit: "count",
        quantityKind: "exact",
        category: "dairy",
        confidence: 0.96,
      },
      {
        name: "whole milk",
        quantity: 1,
        unit: "carton",
        quantityKind: "exact",
        category: "dairy",
        confidence: 0.91,
      },
      {
        name: "butter",
        quantity: 250,
        unit: "g",
        quantityKind: "estimate",
        category: "dairy",
        confidence: 0.85,
      },
      {
        name: "all-purpose flour",
        quantity: 1000,
        unit: "g",
        quantityKind: "estimate",
        category: "pantry",
        confidence: 0.8,
      },
      {
        name: "banana",
        quantity: 3,
        unit: "count",
        quantityKind: "exact",
        category: "produce",
        confidence: 0.93,
      },
      {
        name: "maple syrup",
        quantity: 0,
        unit: "ml",
        quantityKind: "unknown",
        category: "condiment",
        confidence: 0.55,
      },
    ],
    notes: "Mock inventory: breakfast ingredients with one uncertain quantity.",
  },
  {
    items: [
      {
        name: "chicken breast",
        quantity: 2,
        unit: "count",
        quantityKind: "exact",
        category: "meat",
        confidence: 0.89,
      },
      {
        name: "bell pepper",
        quantity: 3,
        unit: "count",
        quantityKind: "exact",
        category: "produce",
        confidence: 0.92,
      },
      {
        name: "jasmine rice",
        quantity: 800,
        unit: "g",
        quantityKind: "estimate",
        category: "grain",
        confidence: 0.84,
      },
      {
        name: "soy sauce",
        quantity: 300,
        unit: "ml",
        quantityKind: "estimate",
        category: "condiment",
        confidence: 0.78,
      },
      {
        name: "ginger",
        quantity: 50,
        unit: "g",
        quantityKind: "estimate",
        category: "produce",
        confidence: 0.6,
      },
      {
        name: "green onion",
        quantity: 1,
        unit: "bunch",
        quantityKind: "estimate",
        category: "produce",
        confidence: 0.7,
      },
    ],
    notes: "Mock inventory: stir-fry ingredients.",
  },
];
