import type { CSSProperties } from "react";
import { StyleSheet } from "react-native";

import { colors } from "../constants/theme";

export const webVideoStyle: CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "cover",
  backgroundColor: colors.earth950,
};

export const styles = StyleSheet.create({
  loading: { flex: 1, backgroundColor: colors.canvas },
  safe: { flex: 1, backgroundColor: colors.canvas },
  shell: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 112,
    backgroundColor: colors.canvas,
  },
  shellBleed: { paddingHorizontal: 0, paddingTop: 0 },
  shellHideNav: { paddingBottom: 24 },
  onboarding: {
    flex: 1,
    minHeight: "100%",
    paddingHorizontal: 24,
    paddingTop: 44,
    paddingBottom: 40,
    backgroundColor: colors.canvas,
  },
  flex1: { flex: 1 },
  pushBottom: { marginTop: "auto", paddingTop: 32 },
  mt8: { marginTop: 8 },
  mt12: { marginTop: 12 },
  mt16: { marginTop: 16 },
  mt20: { marginTop: 20 },
  mt24: { marginTop: 24 },
  mt28: { marginTop: 28 },
  mt32: { marginTop: 32 },
  serifHero: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 44,
    lineHeight: 45,
    color: colors.earth950,
  },
  serifTitle: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 40,
    lineHeight: 42,
    color: colors.earth950,
  },
  serifSubTitle: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 32,
    lineHeight: 36,
    color: colors.earth950,
  },
  bodyText: {
    maxWidth: 310,
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 14,
    lineHeight: 21,
    color: colors.earth600,
  },
  bodyDark: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 14,
    color: colors.earth800,
  },
  cardBody: {
    marginTop: 4,
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: colors.earth600,
  },
  eyebrow: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    color: colors.earth600,
  },
  warmEyebrow: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    color: colors.warm,
  },
  leafEyebrow: {
    fontFamily: "InstrumentSans_700Bold",
    fontSize: 10,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: colors.leaf,
  },
  stepList: { marginTop: 40, gap: 16 },
  infoCardRow: {
    flexDirection: "row",
    gap: 16,
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  warmIconBox: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: colors.warmSoft,
  },
  warmSolidBox: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: colors.warm,
    borderWidth: 4,
    borderColor: "rgba(198,106,43,0.2)",
  },
  cardTitle: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    lineHeight: 19,
    color: colors.earth950,
  },
  smallCenter: {
    marginTop: 12,
    textAlign: "center",
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 11,
    color: colors.earth600,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    color: colors.canvas,
  },
  inline: { flexDirection: "row", alignItems: "center", gap: 6 },
  inlineWide: { flexDirection: "row", alignItems: "center", gap: 12 },
  rowTop: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowBetweenEnd: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  softPanel: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: "rgba(244,238,230,0.7)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  pill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pillText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  largeMetric: {
    marginTop: 6,
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 24,
    color: colors.earth950,
  },
  rightSmall: {
    textAlign: "right",
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 12,
    color: colors.earth600,
  },
  strong: { fontFamily: "InstrumentSans_600SemiBold", color: colors.earth950 },
  progressTrack: {
    height: 6,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.earth200,
  },
  progressFill: { height: "100%", borderRadius: 999 },
  sectionTitle: {
    marginBottom: 12,
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    color: colors.earth600,
  },
  sessionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  foodTile: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.warmSoft,
  },
  emojiLarge: { fontSize: 28 },
  emojiMed: { fontSize: 24 },
  roundWarm: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: colors.warm,
  },
  tiny: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 11,
    color: colors.earth600,
  },
  twoCol: { flexDirection: "row", gap: 12, marginTop: 12 },
  tileCard: {
    flex: 1,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  leafCard: {
    backgroundColor: colors.leafSoft,
    borderColor: "rgba(63,138,99,0.15)",
  },
  warmCard: {
    backgroundColor: colors.warmSoft,
    borderColor: "rgba(198,106,43,0.15)",
  },
  smallFoodTile: {
    width: 40,
    height: 40,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.earth100,
  },
  smallWhiteTile: {
    width: 40,
    height: 40,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  tileTitle: {
    marginBottom: 4,
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 14,
    lineHeight: 18,
    color: colors.earth950,
  },
  scanCard: {
    marginTop: 24,
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.earth950,
  },
  scanEyebrow: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1.6,
    textTransform: "uppercase",
    color: "rgba(250,234,219,0.9)",
  },
  scanTitle: {
    marginTop: 4,
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 22,
    color: colors.canvas,
  },
  scanBody: {
    marginTop: 4,
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: "rgba(252,250,247,0.7)",
  },
  shotSummary: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 8,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  shotStack: { flexDirection: "row" },
  shotThumb: {
    width: 36,
    height: 36,
    marginRight: -8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.earth950,
  },
  whiteStrong: { fontFamily: "InstrumentSans_600SemiBold", color: colors.canvas },
  dividerRow: { marginVertical: 24, flexDirection: "row", alignItems: "center", gap: 12 },
  divider: { flex: 1, height: 1, backgroundColor: colors.earth200 },
  dividerText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1.8,
    textTransform: "uppercase",
    color: colors.earth600,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  searchInput: {
    flex: 1,
    height: 34,
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 14,
    color: colors.earth950,
  },
  addButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.earth100,
  },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  darkChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.earth950,
  },
  darkChipText: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 12,
    color: colors.canvas,
  },
  lightChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  lightChipText: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 12,
    color: colors.earth950,
  },
  pantryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  pantryItem: {
    width: "30.7%",
    minHeight: 88,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  pantryActive: {
    backgroundColor: colors.warmSoft,
    borderColor: "rgba(198,106,43,0.3)",
  },
  pantryText: {
    textAlign: "center",
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 11,
    color: colors.earth950,
  },
  warmText: { color: colors.warm },
  recipeHero: {
    height: 300,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  recipeEmoji: { fontSize: 72, opacity: 0.82 },
  topLeft: { position: "absolute", left: 16, top: 16 },
  suggested: {
    position: "absolute",
    top: 16,
    right: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(252,250,247,0.9)",
  },
  suggestedText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.earth800,
  },
  recipeBody: {
    marginTop: -24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 4,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: colors.canvas,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 20,
    backgroundColor: "rgba(244,238,230,0.7)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  metaRowWhite: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  metaCell: { flex: 1, alignItems: "center" },
  metaDivider: { width: 1, alignSelf: "stretch", backgroundColor: colors.earth200 },
  metaLabel: {
    marginTop: 4,
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.earth600,
  },
  metaValue: {
    marginTop: 2,
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    color: colors.earth950,
  },
  ingredientChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.earth200,
  },
  ingredientText: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 14,
    color: colors.earth950,
  },
  coachNote: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.warmSoft,
    borderWidth: 1,
    borderColor: "rgba(198,106,43,0.15)",
  },
  coachQuote: {
    marginTop: 4,
    fontFamily: "InstrumentSerif_400Regular_Italic",
    fontSize: 19,
    lineHeight: 24,
    color: colors.earth950,
  },
  textButton: { paddingVertical: 14, alignItems: "center" },
  textButtonText: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 14,
    color: colors.earth800,
  },
  liveSafe: { flex: 1, backgroundColor: colors.earth950 },
  liveViewport: { flex: 1, overflow: "hidden", backgroundColor: colors.earth950 },
  panEmoji: {
    position: "absolute",
    alignSelf: "center",
    top: "42%",
    fontSize: 64,
    opacity: 0.3,
  },
  liveTop: {
    position: "absolute",
    top: 24,
    left: 20,
    right: 20,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  liveCenter: { alignItems: "center", gap: 8 },
  livePill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  livePillText: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 11,
    color: colors.white,
  },
  dots: { flexDirection: "row", alignItems: "center", gap: 4 },
  dot: { height: 6, borderRadius: 999 },
  dotWarm: { width: 6, backgroundColor: colors.warm },
  dotActive: { width: 16, backgroundColor: colors.white },
  dotMuted: { width: 6, backgroundColor: "rgba(255,255,255,0.3)" },
  recordingBottom: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 24,
    zIndex: 2,
  },
  recordingPanel: {
    gap: 12,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "rgba(252,250,247,0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  recordingTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  recordingTitle: {
    flex: 1,
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 15,
    color: colors.earth950,
  },
  recordingBody: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 12,
    lineHeight: 18,
    color: colors.earth600,
  },
  recordingError: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 12,
    lineHeight: 18,
    color: colors.warm,
  },
  recordButton: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: 18,
    backgroundColor: colors.warm,
  },
  stopButton: { backgroundColor: colors.earth950 },
  recordButtonDisabled: { opacity: 0.55 },
  recordButtonIcon: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  recordButtonText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    color: colors.white,
  },
  secondaryRecordButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    backgroundColor: colors.earth100,
  },
  secondaryRecordButtonText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    color: colors.earth950,
  },
  recordingStatus: {
    position: "absolute",
    top: 92,
    alignSelf: "center",
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.42)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.warm,
  },
  recordingStatusText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    color: colors.white,
  },
  recordingBackdropContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  recordingBackdropTitle: {
    marginTop: 20,
    textAlign: "center",
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 28,
    color: colors.white,
  },
  recordingBackdropBody: {
    marginTop: 8,
    maxWidth: 320,
    textAlign: "center",
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 13,
    lineHeight: 19,
    color: "rgba(255,255,255,0.72)",
  },
  sideControls: {
    position: "absolute",
    right: 16,
    top: "42%",
    gap: 8,
  },
  liveCircle: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  liveBottom: { position: "absolute", left: 16, right: 16, bottom: 24, gap: 12 },
  coachBubble: {
    flexDirection: "row",
    gap: 12,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.95)",
  },
  pulseWrap: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: colors.warmSoft,
  },
  pulseDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.warm,
  },
  coachLabel: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.earth600,
  },
  coachText: {
    marginTop: 3,
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 15,
    lineHeight: 20,
    color: colors.earth950,
  },
  guidanceCard: {
    padding: 20,
    borderRadius: 28,
    backgroundColor: colors.canvas,
  },
  guidanceTitle: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 23,
    lineHeight: 27,
    color: colors.earth950,
  },
  buttonRow: { flexDirection: "row", gap: 8, marginTop: 16 },
  backButton: {
    flex: 1,
    paddingVertical: 13,
    alignItems: "center",
    borderRadius: 16,
    backgroundColor: colors.earth100,
  },
  backButtonText: {
    fontFamily: "InstrumentSans_500Medium",
    color: colors.earth950,
  },
  nextButton: {
    flex: 2,
    paddingVertical: 13,
    alignItems: "center",
    borderRadius: 16,
    backgroundColor: colors.earth950,
  },
  nextButtonText: {
    fontFamily: "InstrumentSans_600SemiBold",
    color: colors.canvas,
  },
  iconButtonLight: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "rgba(252,250,247,0.9)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  iconButtonDark: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  center: { alignItems: "center", paddingTop: 8 },
  centerText: { marginTop: 8, textAlign: "center" },
  leafRound: {
    width: 56,
    height: 56,
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    backgroundColor: colors.leafSoft,
    borderWidth: 1,
    borderColor: "rgba(63,138,99,0.15)",
  },
  feedbackCard: {
    flex: 1,
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
  },
  whitePanel: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  noticeRow: { flexDirection: "row", alignItems: "flex-start", gap: 12, marginTop: 12 },
  noticeDot: { width: 6, height: 6, marginTop: 7, borderRadius: 3 },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  smallEarthBox: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.earth100,
  },
  savingsSummary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.leafSoft,
    borderWidth: 1,
    borderColor: "rgba(63,138,99,0.15)",
  },
  whiteIconBox: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  moneyText: {
    marginTop: 4,
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 32,
    color: colors.earth950,
  },
  warmSmall: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 11,
    color: colors.warm,
  },
  leafSmall: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 11,
    color: colors.leaf,
  },
  swapCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 10,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  swapLine: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 14,
    color: colors.earth950,
  },
  strike: { color: colors.earth600, textDecorationLine: "line-through" },
  savePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.leafSoft,
  },
  saveText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 11,
    color: colors.leaf,
  },
  saleCard: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: colors.warmSoft,
    borderWidth: 1,
    borderColor: "rgba(198,106,43,0.15)",
  },
  saleTitle: {
    marginTop: 8,
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 22,
    lineHeight: 26,
    color: colors.earth950,
  },
  tipCard: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  avatar: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: colors.warmSoft,
  },
  avatarText: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 22,
    color: colors.warm,
  },
  profileName: {
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 24,
    color: colors.earth950,
  },
  circleWhite: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  skillRow: { marginBottom: 16 },
  savedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
    padding: 12,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  savedEmoji: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.earth100,
  },
  prefBox: {
    overflow: "hidden",
    borderRadius: 24,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  prefRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.earth200,
  },
  settingsRow: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
  },
  cameraSafe: { flex: 1, backgroundColor: colors.earth950 },
  cameraTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
  },
  iconButtonSpacer: { width: 40, height: 40 },
  cameraViewport: { flex: 1, overflow: "hidden" },
  permissionPanel: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  cameraIconLarge: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: colors.warmSoft,
  },
  cameraTitle: {
    marginTop: 20,
    textAlign: "center",
    fontFamily: "InstrumentSerif_400Regular",
    fontSize: 28,
    color: colors.white,
  },
  cameraBody: {
    marginTop: 8,
    maxWidth: 320,
    textAlign: "center",
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 13,
    lineHeight: 19,
    color: "rgba(255,255,255,0.7)",
  },
  cameraBullets: { marginTop: 20, gap: 8 },
  bulletRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  cameraBulletText: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 12,
    color: "rgba(255,255,255,0.7)",
  },
  cameraShots: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(0,0,0,0.4)",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
  },
  cameraShotTitle: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 10,
    letterSpacing: 1.6,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.7)",
  },
  cameraClear: {
    fontFamily: "InstrumentSans_400Regular",
    fontSize: 11,
    color: "rgba(255,255,255,0.6)",
  },
  cameraThumbWrap: { marginTop: 8, marginRight: 8 },
  cameraThumb: {
    width: 64,
    height: 64,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cameraThumbLabel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
    textAlign: "center",
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 8,
    color: colors.white,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  cameraControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: colors.earth950,
  },
  shutter: {
    width: 72,
    height: 72,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 36,
    backgroundColor: colors.white,
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.2)",
  },
  shutterInner: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.earth950,
  },
  doneButton: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: colors.warm,
  },
  doneDisabled: { backgroundColor: "rgba(255,255,255,0.1)" },
  doneText: {
    fontFamily: "InstrumentSans_600SemiBold",
    fontSize: 14,
    color: colors.white,
  },
  doneTextDisabled: { color: "rgba(255,255,255,0.4)" },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: "rgba(252,250,247,0.92)",
    borderTopWidth: 1,
    borderTopColor: "rgba(231,225,216,0.7)",
  },
  navItem: { flex: 1, alignItems: "center", gap: 4 },
  navIcon: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  navIconActive: { backgroundColor: colors.earth950 },
  navText: {
    fontFamily: "InstrumentSans_500Medium",
    fontSize: 10,
    color: colors.earth600,
  },
  navTextActive: { color: colors.earth950 },
});
