/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppSavingsRouteImport } from './routes/app.savings'
import { Route as AppRecipePlanRouteImport } from './routes/app.recipe-plan'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLiveCookingRouteImport } from './routes/app.live-cooking'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipePlanRoute = AppRecipePlanRouteImport.update({
  id: '/recipe-plan',
  path: '/recipe-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveCookingRoute = AppLiveCookingRouteImport.update({
  id: '/live-cooking',
  path: '/live-cooking',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/feedback': typeof AppFeedbackRoute
  '/app/live-cooking': typeof AppLiveCookingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recipe-plan': typeof AppRecipePlanRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/live-cooking': typeof AppLiveCookingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recipe-plan': typeof AppRecipePlanRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/feedback': typeof AppFeedbackRoute
  '/app/live-cooking': typeof AppLiveCookingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recipe-plan': typeof AppRecipePlanRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/feedback'
    | '/app/live-cooking'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/recipe-plan'
    | '/app/savings'
    | '/app/setup'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/feedback'
    | '/app/live-cooking'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/recipe-plan'
    | '/app/savings'
    | '/app/setup'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/feedback'
    | '/app/live-cooking'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/recipe-plan'
    | '/app/savings'
    | '/app/setup'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/savings': {
      id: '/app/savings'
      path: '/savings'
      fullPath: '/app/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipe-plan': {
      id: '/app/recipe-plan'
      path: '/recipe-plan'
      fullPath: '/app/recipe-plan'
      preLoaderRoute: typeof AppRecipePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live-cooking': {
      id: '/app/live-cooking'
      path: '/live-cooking'
      fullPath: '/app/live-cooking'
      preLoaderRoute: typeof AppLiveCookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppLiveCookingRoute: typeof AppLiveCookingRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecipePlanRoute: typeof AppRecipePlanRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeedbackRoute: AppFeedbackRoute,
  AppLiveCookingRoute: AppLiveCookingRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecipePlanRoute: AppRecipePlanRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
